project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - CNAME
  preview:
    browser: true
    port: 4200
    watch-inputs: true
  #base-url: /website/

website:
  title: "Gabriel Passos"
  navbar:
    left:
      - text: "Início"
        href: index.qmd
      - text: "Sobre"
        href: about.qmd
      - text: "Projetos"
        href: projetos.qmd
      - text: "Blog"
        href: blog/index.qmd
  page-footer: "© 2025 Gabriel Caser"

format:
  html:
    theme: darkly
    toc: true
