
project:
  type: website

website:
  title: "Gabriel Passos"
  navbar:
    left:
      - text: "Início"
        href: index.qmd
      - text: "Sobre"
        href: about.qmd
      - text: "Projetos"
        href: projetos.qmd
      - text: "Blog"
        href: blog/index.qmd
  page-footer: "© 2025 Gabriel Passos"
  google-analytics: ""

format:
  html:
    theme: cosmo
    toc: true
