
---
title: "Blog"
format: html
---

# Bem vindo

Bem-vindo ao meu blog. Aqui vou documentar o progresso do projeto de lembretes automatizados.

# Reunião com a Secretaria de Assistência Social (2025-04-23)
Hoje tive uma reunião com a subsecretária de Vitória. Fiquei impressionado o quão entusiasmada ela estava com a ideia, inclusive sugerindo uma série de outras aplicaçÕes. Quando fui fazer a demonstração do código rodando, claro que ele não funcionou como deveria kkcry. Bem, pelo menos consegui explicar e o fiz funcionar de alguma forma. Ela se mostrou aberta a compartilhar os dados do CRAS após eu participar de mais uma reunião com uma outra pessoa da secretaria e assinar um termo de cooperação. Pensei que seria mais difícil, mas talvez consiga acessar os dados mesmo aqui dos EUA! Isso me faz inclusive repensar se devo realmente voltar a morar no ES como estava pretendendo. Bem, o mais legal foi ver como existem pessoas empreendedoras e abertas e dispostas a melhorar o serviço público dentro do Governo!
Pelas minhas estimativas o meu bot terá que enviar em torno de 25 mensagens por dia, dando em torno de 500 por mês. Acho que o Whatsapp não vai me bloquear, mas não tenho certeza.

# Começando o projeto MVP (2025-04-19)

Hoje fiz em 3 horas o MVP do projeto de lembretes automatizados. O MVP consiste em um bot que envia mensagens no WhatsApp para os usuários cadastrados. O bot é capaz de enviar mensagens personalizadas e programadas para cada usuário, com base nas informações fornecidas no cadastro. Escrevi o código em Python, utilizando a biblioteca pywhatkit para enviar mensagens no WhatsApp. Testei enviando para 3 amigos e para mim mesmo no Zap. A mensagem ficou com essa cara:

```python
f"""Olá, *{nome}*! 😊
    Este é um lembrete do seu *atendimento no CRAS* 
    - 🗓️ Data: {data} (*Amanhã*)
    - 📍 Endereço: {endereco_cras}
    - 🤝 Qualquer dúvida, estamos à disposição."""
```

A estrutua da função que executa o envio de mensagens é bem simples:

```python
kit.sendwhatmsg(telefone, mensagem, hora_envio, minuto_envio, wait_time = 20, tab_close = True, close_time = 5)
```


A ideia de bloco de 3 horas é baseada em um episódio do Podcast do Tim Ferris, que menciona que você deve focar em fazer uma tarefa importante por dia, reservando no mínimo 2h, INIMTERRUPTAS, para isso. Essa tarefa tem que cumprir pelo menos um desses dois itens: (i) te deixar com uma sensação de dever cumprido pelo resto do dia; (ii) tornar as demais tarefas mais fáceis ou irrelavantes. É impressionante como minha produtividade mudou após eu definir esses espaços de 2h (para tarefas que já tenho uma ideia do que fazer) ou 3h (para tarefas que não tenho ideia do que fazer). O resultado é que consigo fazer mais em menos tempo, e ainda tenho tempo livre.

Também comecei a ler o Lean Startup e acho que vai me ajudar nesse processo. 

